apiVersion: v1
kind: Service
metadata:
  name: myproject-loadbalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: udacity.capstone.project.chimezie.com
spec:
  type: LoadBalancer
  selector:
    app: myproject
  ports:
    - port: 80
      targetPort: 80